### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by scott-wyatt** [langateam/trailpack-graphql#1]
@tjwebb, where would be a good place here to start if I was able to help?

**Comment by tjwebb** [comment]
helping write tests :)  I was able to devote about a week to getting this thing finally designed and built, but it's pretty badly tested.

**Comment by tjwebb** [comment]
@scott-wyatt do you think I should add a bounty for this?

**Comment by scott-wyatt** [comment]
That would be awesome! I've been itching to play with this.

**Comment by clayrisser** [comment]
How do I use this with trailpack-waterline?
